{"name": "Validate successful login -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@id='header']/h1\"}\n  (Session info: chrome=129.0.6668.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7F2BCFDA5+29557]\n\t(No symbol) [0x00007FF7F2B42240]\n\t(No symbol) [0x00007FF7F29FB6EA]\n\t(No symbol) [0x00007FF7F2A4FA15]\n\t(No symbol) [0x00007FF7F2A4FC6C]\n\t(No symbol) [0x00007FF7F2A9BB07]\n\t(No symbol) [0x00007FF7F2A7753F]\n\t(No symbol) [0x00007FF7F2A988A3]\n\t(No symbol) [0x00007FF7F2A772A3]\n\t(No symbol) [0x00007FF7F2A412DF]\n\t(No symbol) [0x00007FF7F2A42451]\n\tGetHandleVerifier [0x00007FF7F2EFDCBD+3363469]\n\tGetHandleVerifier [0x00007FF7F2F49B47+3674391]\n\tGetHandleVerifier [0x00007FF7F2F3EAEB+3629243]\n\tGetHandleVerifier [0x00007FF7F2C8FC66+815670]\n\t(No symbol) [0x00007FF7F2B4D6EF]\n\t(No symbol) [0x00007FF7F2B492B4]\n\t(No symbol) [0x00007FF7F2B49450]\n\t(No symbol) [0x00007FF7F2B381FF]\n\tBaseThreadInitThunk [0x00007FFD027C257D+29]\n\tRtlUserThreadStart [0x00007FFD0382AF28+40]\n\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 39, in step_impl\n    homeTitle = context.driver.find_element(By.XPATH, \"//*[@id='header']/h1\").text\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I navigate to homepage", "status": "passed", "start": 1726872655115, "stop": 1726872655128}, {"name": "When I enter username as \"<userName>\"", "status": "passed", "start": 1726872655128, "stop": 1726872658320}, {"name": "And I enter password as \"<password>\"", "status": "passed", "start": 1726872658320, "stop": 1726872661531}, {"name": "And I click on Continue button", "status": "passed", "start": 1726872661531, "stop": 1726872666636}, {"name": "When I validate the page title", "status": "passed", "start": 1726872666636, "stop": 1726872666648}, {"name": "When I enter username as \"testUser\"", "status": "passed", "start": 1726872666648, "stop": 1726872669819}, {"name": "And I enter password as \"Test1234\"", "status": "passed", "start": 1726872669819, "stop": 1726872672988}, {"name": "And I click on Continue button", "status": "passed", "start": 1726872672988, "stop": 1726872678104}, {"name": "Then I verify the user has logged in successfully", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@id='header']/h1\"}\n  (Session info: chrome=129.0.6668.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7F2BCFDA5+29557]\n\t(No symbol) [0x00007FF7F2B42240]\n\t(No symbol) [0x00007FF7F29FB6EA]\n\t(No symbol) [0x00007FF7F2A4FA15]\n\t(No symbol) [0x00007FF7F2A4FC6C]\n\t(No symbol) [0x00007FF7F2A9BB07]\n\t(No symbol) [0x00007FF7F2A7753F]\n\t(No symbol) [0x00007FF7F2A988A3]\n\t(No symbol) [0x00007FF7F2A772A3]\n\t(No symbol) [0x00007FF7F2A412DF]\n\t(No symbol) [0x00007FF7F2A42451]\n\tGetHandleVerifier [0x00007FF7F2EFDCBD+3363469]\n\tGetHandleVerifier [0x00007FF7F2F49B47+3674391]\n\tGetHandleVerifier [0x00007FF7F2F3EAEB+3629243]\n\tGetHandleVerifier [0x00007FF7F2C8FC66+815670]\n\t(No symbol) [0x00007FF7F2B4D6EF]\n\t(No symbol) [0x00007FF7F2B492B4]\n\t(No symbol) [0x00007FF7F2B49450]\n\t(No symbol) [0x00007FF7F2B381FF]\n\tBaseThreadInitThunk [0x00007FFD027C257D+29]\n\tRtlUserThreadStart [0x00007FFD0382AF28+40]\n\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 39, in step_impl\n    homeTitle = context.driver.find_element(By.XPATH, \"//*[@id='header']/h1\").text\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "Screenshot", "source": "03b29787-dc25-469c-a296-828219daa300-attachment.png", "type": "image/png"}], "start": 1726872678104, "stop": 1726872678328}], "parameters": [{"name": "userName", "value": "testUser"}, {"name": "password", "value": "Test1234"}], "start": 1726872647584, "stop": 1726872680646, "uuid": "a69f3361-de8d-425d-a426-c189c9168427", "historyId": "b6a52984e1a196325a55b37b9163cd47", "fullName": "Calories Calculation functionality: Validate successful login", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Login"}, {"name": "feature", "value": "Calories Calculation functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}